export const ADD_USER_INFO = "ADD_USER_INFO";
export const MONTH_DATA = "MONTH_DATA";
export const GET_SUCCESSFUL_DATA = "GET_SUCCESSFUL_DATA";
export const URL_CONFIRMATION = "URL_CONFIRMATION";
export const URL_RESULT = "URL_RESULT";
